### ISSUE TITLE
uonet-request-signer-node is not updated on npm.

### ISSUE THREAD

**Issue by n3oney** [wulkanowy/uonet-request-signer#5]
I've made a pull reqest to the node request signer and it got accepted, but the module hasn't been updated on NPM.
Could you please update it? Thanks.

**Comment by mklkj** [comment]
Hey, I am sorry that you had to wait. I published a moment ago [version 0.1.1 of uonet-request-signer-node](https://www.npmjs.com/package/@wulkanowy/uonet-request-signer-node/v/0.1.1)
